version: '3.8'
services:
  db:
    image: postgres:11.5
    restart: always
    container_name: postgres_container4
    ports:
      - "5055:5432"

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    volumes:
      - ./infastructure/db:/docker-entrypoint-initdb.d
